config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  mount ActionCable.server => '/cable'
  resources :quests do
    resources :solutions do
       post 'payout'
     end
  end
  get :next_quest, to: 'quests#next'

  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/get_started', to: 'home#get_started'
  get '/creators', to: 'home#creators'
  get '/roadmap', to: 'home#roadmap'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ### API ROUTES
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/login', to: 'auth#login'
      resources :quests
    end
  end

end

app/models/quest.rb
class Quest < ApplicationRecord
  require 'iota'

  before_create :create_address

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  enum status: [:active, :payout_proccessed, :solved]

  belongs_to :project, optional: true

  belongs_to :creator, class_name: 'User'
  belongs_to :solver, class_name: 'User', optional: true

  has_many :solutions
  has_one :solution

  validates :title, :slug, presence: true
  validates :title, length: { minimum: 5, maximum: 81 }

  def payout message

    utils = IOTA::Utils::InputValidator.new
    return false unless utils.isAddress(message.address)


    self.solver = solution.creator if solution.creator
    self.solution = solution
    SolutionPayoutJob.perform_later(self, solution)
    self.payout_proccessed!

   return true
  end

  private
  def create_address
    # Create client directly with provider
    client = IOTA::Client.new(provider: 'https://nodes.devnet.iota.org')

    # now you can start using all of the functions
    status, data = client.api.getNodeInfo

    ## create and save seed
    self.seed = (1..81).map{'ABCDEFGHIJKLMNOPQRSTUVWXYZ9'[SecureRandom.random_number(27)]}.join('')

    ## create and save latest address
    account = IOTA::Models::Account.new(client, self.seed)
    account.getAccountDetails({})

    self.latest_address = account.latestAddress
    self.status = :active
  end
end

app/controllers/api/v1/quests_controller.rb
class Api::V1::QuestsController < ApiController
  skip_before_action :verify_authenticity_token
  before_action :authorize_request, only: [:create]
  before_action :set_quest, only: [:show]
  
  # GET /api/v1/quests
  def index
    @quests = Quest.all
    respond_to do |format|
      if @quests
        format.json { render "quests/index", quests: @quests, status: :ok}
      else
        format.json { render json: @quests, status: :empty }
      end
    end
  end

  # POST /api/v1/quests
  def create
  @quest = current_user.created_quests.new(quest_params)
    respond_to do |format|
      if @quest.save
        format.json { render "quests/show", status: :created, location: @quest }
      else
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /api/v1/quests/:slug
  def show
    respond_to do |format|
      if @quest
        format.json { render "quests/show", quest: @quest, status: :ok}
      else
        format.json { render json: @quest, status: :not_found }
      end
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_quest
    @quest = Quest.find_by(slug: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def quest_params
    params.require(:quest).permit(:title)
  end

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  load_and_authorize_resource except: [:index, :show, :next]
  skip_authorize_resource only: [:index, :show, :next]
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all.where(status: :active)
    @sovled_quests = Quest.all.where(status: :inactive).order(payed_at: :asc)
    @open_quests = Quest.all.where(status: :active)
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
    @solution = Solution.new
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = current_user.created_quests.new(quest_params)

    respond_to do |format|
      if @quest.save
        ActionCable.server.broadcast 'web_notifications_channel', quest: @quest

        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def next
  @quest = Quest.first
  respond_to do |format|
    format.html { redirect_to @quest }
    format.json { render :show, status: :ok, location: @quest }
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:title, :project_id)
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>
      <ul>
      <% quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" data_type="title">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: 'My awesome quest', autofocus: true %>
  </div>

  <div class="form-group" data_type="title">
    <%= form.label :title %>
    
    <%= collection_select(:quest, :project_id, Project.all, :id, :name, prompt: true)
 %>
  </div>

  <div class="form-actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/quests/edit.html.erb
<% content_for :title, "Quests - Edit quest" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">Edit Quest</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-6 ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container">
          <%= link_to 'Back', quest_path(@quest) %>
        </div>
        <div class="box">
          <%= render 'form', quest: @quest %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quests/index.html.erb
<% content_for :title, "Quests - Discover" %>
<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1>Discover</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">OPEN QUESTS</h2>
        <a href="<%= new_quest_path %>" class="btn btn-primary m-t-30">Create your quest</a>
      </div>
      <%= render "shared/ornaments/bg-small" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <% @open_quests.each do |quest| %>
          <a href="<%= quest_path(quest) %>" class="box box-item box-dark linked align-items-start justify-content-between">
            <div class="box-body">
              <h4><%= quest.title %></h4>
              <span style="opacity: .5;">Created by: <%= quest.creator.username %></span>
            </div>
            <div class="box-footer">
              <% if quest.balance.nil? %>
              <span class="box-counter">
                <%= image_tag "icons/iota.svg" %>
                <span>0 IOTA</span>
              </span>
              <% else %>
              <span><%= quest.balance %></span>
              <span class="box-counter">
                <%= image_tag "icons/iota.svg" %>
                <span><%= quest.balance %></span>
              </span>
              <% end %>
              <% if quest.solutions.count == 0 %>
              <span class="box-counter">
                <%= image_tag "icons/solution.svg" %>
                <span>0 Solution</span>
              </span>
              <% else %>
              <span class="box-counter">
                <%= image_tag "icons/solution.svg" %>
                <span><%= quest.solutions.count %></span>
              </span>
              <% end %>
            </div>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section content justify-content-start decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">CLOSED QUESTS</h2>
        <a href="mailto: quests@worldofmind.org?subject=Request for beta testing&body=Tell us something about you and why you would like to help us testing!" class="btn btn-primary m-t-30">Create your quest</a>
      </div>
      <%= render "shared/ornaments/bg-small" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <% @open_quests.each do |quest| %>
          <a href="<%= quest_path(quest) %>" class="box box-item linked align-items-start justify-content-between">
            <div class="box-body">
              <h4><%= quest.title %></h4>
              <span style="opacity: .5;">Created by: <%= quest.creator.username %></span>
            </div>
            <div class="box-footer">
              <% if quest.balance.nil? %>
              <span class="box-counter">
                <%= image_tag "icons/iota-dark.svg" %>
                <span>0 IOTA</span>
              </span>
              <% else %>
              <span><%= quest.balance %></span>
              <span class="box-counter">
                <%= image_tag "icons/iota-dark.svg" %>
                <span><%= quest.balance %></span>
              </span>
              <% end %>
              <% if quest.solutions.count == 0 %>
              <span class="box-counter">
                <%= image_tag "icons/solution-dark.svg" %>
                <span>0 Solution</span>
              </span>
              <% else %>
              <span class="box-counter">
                <%= image_tag "icons/solution-dark.svg" %>
                <span><%= quest.solutions.count %></span>
              </span>
              <% end %>
            </div>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quests/new.html.erb
<% content_for :title, "Quests - Create a quest" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">New Quest</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-6 ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container">
          <%= link_to root_path do %>Back to Home<% end %>
        </div>
        <div class="box">
          <%= render 'form', quest: @quest %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quests/show.html.erb
<% content_for :title, "Quests -  #{ @quest.title}" %>
<% if @quest.solved? %>
  <div class="alert alert-warning" role="alert">
    <strong>Closed!</strong> This quest is solved!
  </div>
<% elsif @quest.payout_proccessed? %>
<div class="alert alert-warning" role="alert">
  <strong>Closed!</strong> This payout is processig!
</div>
<% end %>
<div class="section page-title bg-primary p-t-25 p-b-100" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center"><%= @quest.title %></h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start pull-top">
  <div class="container">
    <div class="row">
      <div class="col-lg ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container breadcrumb-container__pull-top">
          <%= link_to root_path do %>Back to Home<% end %>
        </div>
        <div class="box m-b-30">
          <% if current_user&.id == @quest.creator_id %>
          <div class="box-menu top-right">
            <%= link_to edit_quest_path(@quest), id:'edit-btn', class: 'btn btn-primary btn-icon', data: {toggle: 'tooltip', placement: 'bottom'}, title: "Edit your quest" do %>
              <%= image_tag "icons/edit.svg" %>
            <% end %>
          </div>
          <% end %>
          <div class="box-body">
            <div id="countdown" class="box-countdown mr-auto ml-auto" >
              <h5 class="m-b-0" style="">Created by <%= @quest.creator.username %>, <%= time_ago_in_words @quest.created_at %> ago</h5>
              <hr>
            </div>

            <div class="react-balance">
              <%= react_component("Balance", { address: @quest.latest_address }) if @quest.active? %>
              <div class="balance-footer">
                <% if @quest.active? %>
                  <div class="buttonCopyAddressk" data-toggle="tooltip" data-placement="bottom" title="<%= @quest.latest_address %>"  data-address="<%= @quest.latest_address %>">
                    <%= @quest.latest_address.truncate(9, omission: "...#{@quest.latest_address.last(3)}") %>
                  </div>
                  <button type="button" class="btn btn-dark buttonCopyAddressk" style="margin-bottom: 10px;" data-address="<%= @quest.latest_address %>">Copy address</button>
                <% elsif @quest.payout_proccessed? %>
                <p>Payout is done soon...</p>
                <% else %>
                <p>Payed out <%= time_ago_in_words @quest.payed_at  %> ago to  <%= link_to "solution", quest_path(@quest, anchor: "solution-#{@quest.solutions.find_index(@quest.solution) + 1}") %></p>
                <% end %>
                <%= link_to "Check on TheTangle.org", "https://thetangle.org/address/#{@quest.latest_address}", target: '_blank' %>
              </div>

              <div class="react-donatorsList">
                <%= react_component("DonatorsList", { address: @quest.latest_address }) if @quest.active? %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 mr-auto ml-auto">
        <h2 class="m-b-30">Suggested solutions</h2>
        <%= render 'solutions/solution_fields', solution: @solution, quest: @quest if @quest.active? || @quest.payout_proccessed? %>
        <% @quest.solutions.each_with_index do |solution, index| %>
          <div id="solution-<%= index + 1 %>" class="box m-b-30 <%= "text-white box-success" if  @quest.solved? && solution == @quest.solution %>">
            <div class="box-title">
              <span>Solution #<%= index + 1 %></span>
            </div>
            <div class="options-wrapper options-wrapper__small">
              <% if @quest.active? && current_user == @quest.creator %>
                <%= button_to "Payout", quest_solution_payout_path(@quest, solution), class: 'btn btn-primary btn-sm' %>
              <% end %>
              <button type="button" class="btn btn-dark btn-sm buttoncopySolutionLink" style="margin-left: 15px;">Copy Solution Link</button>
            </div>
            <% unless solution.text.nil? %>
            <div><%=sanitize solution.text %></div>
            <% end %>
            <p style="opacity: .5; margin-bottom: 0;">Posted by <%= solution.creator ? solution.creator.username : 'anonymous' %>, <%= time_ago_in_words solution.created_at if solution.created_at %> ago</p>
            <% if @quest.active? && current_user == @quest.solver %>
            <% elsif solution == @quest.solved? && !@quest.payout_proccessed? %>
              <p>Payed out <%= @quest.payed_amount ? @quest.payed_amount : "unknown" %> IOTA <%= time_ago_in_words @quest.payed_at  %> ago.</p>
              <a href="https://thetangle.org/address/<%= @quest.solution.address %>" target="_blank">Watch payment on TheTangle.org</a>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>