config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  mount ActionCable.server => '/cable'
  resources :quests do
    resources :solutions do
       post 'payout'
     end
  end
  get :next_quest, to: 'quests#next'

  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/get_started', to: 'home#get_started'
  get '/creators', to: 'home#creators'
  get '/roadmap', to: 'home#roadmap'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ### API ROUTES
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/login', to: 'auth#login'
      resources :quests
    end
  end

end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md footer-top ">
        <a class="navbar-brand" href="<%= root_path %>">
          <%= image_tag("logo.svg") %>
        </a>
        <ul class="footer-nav">
          <li class="nav-item <%= "active" if request.path == '/get_started' %>"><%= link_to "Get Started", get_started_path, class: 'nav-link' %></li>
          <!-- <li class="nav-item <#%= "active" if request.path == '/creators' %>""><%= link_to "Creators", creators_path, class: "nav-link" %></li> -->
          <li class="nav-item <%= "active" if request.path == '/roadmap' %>""><%= link_to "Roadmap", roadmap_path, class: "nav-link" %></li>
          <li class="nav-item <%= "active" if request.path == '/quests' %>""><%= link_to "Discover", quests_path, class: "nav-link" %></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="footer-divider m-t-50 m-b-50">
          <hr>
          <span>© 2018 World of Mind</span>
          <div class="caret-down" id="caret-top">
            <%= image_tag "icons/caret.svg" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md footer-bottom">
        <span>Have a nice <%= Time.now.strftime("%A") %>!</span>
        <span>Made with <%= image_tag "icons/heart.svg" %> and <a href="https://www.iota.org" target="_blank"><%= image_tag "icons/iota.svg" %></a> by <a href="https://ecosystem.iota.org/users/huhn" target="_blank">huhn</a> and <a href="https://ecosystem.iota.org/users/rep0x" target="_blank">r3p0x</a> </span>
        <div class="footer-links">
          <%= link_to "Privacy Policy", privacy_path %> •
          <a href="mailto: quests@worldofmind.org?subject=Contact">Contact</a>
        </div>
      </div>
    </div>
  </div>
</footer>
<script>
  $(document).ready(function (){
      $("#caret-top").click(function (){
          $('html, body').animate({
              scrollTop: $("#hero").offset().top
          }, 600);
      });
  });
</script>

app/views/shared/_head.html.erb
<title><%= yield(:title) %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= render 'application/favicon' %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application' %>
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,700,900" rel="stylesheet">

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-lg">
  <div class="meta-nav">
    <ul>
      <li><a href="https://events.worldofmind.org">Events</a></li>
      <li><a href="https://quests.worldofmind.org">Quests</a></li>
      <li style="padding: 2px 10px"><span style="color: white; font-size: 10px; font-weight: bold; opacity: .25; text-transform: uppercase; letter-spacing: 1px;">More services coming soon</span></li>
    </ul>
  </div>
  <a class="navbar-brand <%= "active" if request.path == '/' %>" href="<%= root_path %>">
    <%= image_tag("logo.svg") %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <div class="navbar-toggler-wrapper">
      <span class="line line__top"></span>
      <span class="line line__center"></span>
      <span class="line line__bottom"></span>
    </div>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= "active" if request.path == '/get_started' %>"><%= link_to "Get started", get_started_path, class: "nav-link" %></li>
      <!-- <li class="nav-item <#%= "active" if request.path == '/creators' %>""><%= link_to "Creators", creators_path, class: "nav-link" %></li> -->
      <li class="nav-item <%= "active" if request.path == '/roadmap' %>""><%= link_to "Roadmap", roadmap_path, class: "nav-link" %></li>
      <li class="nav-item <%= "active" if request.path == '/quests' %>"><%= link_to "Discover", quests_path, class: "nav-link notifications" %></li>
      <% if user_signed_in? %>
      <!-- <li class="nav-item icon <#%= "active" if request.path == '/notifications' %>">
        <#%= link_to notifications_path, class: "nav-link notifications", data: {toggle: 'tooltip', placement: 'bottom'}, title: "Notifications" do %>
          <#%= image_tag "icons/notification.svg", class: 'm-r-0' %>
        <#% end %>
      </li> -->

      <li class="nav-item icon dropdown <%= "active" if request.path_info.include?('quests') %>">
        <%= link_to quests_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle quests", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
          <%= image_tag "icons/star.svg" %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbar-dropdown">
          <%= link_to "Create a new quest", new_quest_path, class: "dropdown-item" %>
          <% if current_user %>
            <% current_user.created_quests.each do |quest| %>
            <div class="dropdown-divider"></div>
              <%= link_to "#{quest.title}", quest_path(quest), class: "dropdown-item" if quest.id %>
            <% end %>
          <% end %>
        </div>
      </li>
      <li class="nav-item icon dropdown <%= "active" if request.path_info.include?('users') %>">
        <%= link_to root_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle account", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
          <%= image_tag gravatar_image_url(current_user.email, size: 40), height: 30, width: 30, class: "rounded" %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbar-dropdown">
          <% if current_user.admin? %>
            <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= link_to "Projects", projects_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>

      <% else %>
        <li class="nav-item button"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary", style: "color: #fff" %></li>
        <li class="nav-item button"><%= link_to "Log in", new_user_session_path, class: "btn btn-primary", style: "color: #fff" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div>
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>