config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  mount ActionCable.server => '/cable'
  resources :quests do
    resources :solutions do
       post 'payout'
     end
  end
  get :next_quest, to: 'quests#next'

  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/get_started', to: 'home#get_started'
  get '/creators', to: 'home#creators'
  get '/roadmap', to: 'home#roadmap'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ### API ROUTES
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/login', to: 'auth#login'
      resources :quests
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @hero_quest = Quest.all.where(status: :active).first
     @open_quest_count = Quest.all.where(status: :active).count
     @sovled_quest_coun = Quest.all.where(status: :solved).count
  end

  def get_started
  end

  def creators
  end

  def roadmap
  end

  def privacy
  end
end

app/views/home/_hero_animation.html.erb
<div class="particles">

</div>

<div class="animation-wrapper">
  <div class="animation-container">
    <div class="circle-wrapper">
      <%= image_tag "hero/circle/circle-path_1.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_2.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_3.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_4.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_5.svg", class:"circle-outline size-md" %>
      <%= image_tag "hero/circle/circle-path_6.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_7.svg", class:"circle-outline transparent-20 size-sm" %>
      <%= image_tag "hero/circle/circle-path_8.svg", class:"circle-outline size-md" %>
      <%= image_tag "hero/circle/circle-path_9.svg", class:"circle-outline size-lg" %>
      <%= image_tag "hero/circle/circle-path_10.svg", class:"circle-outline transparent-20 size-sm" %>
      <%= image_tag "hero/circle/circle-path_11.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_12.svg", class:"circle-outline size-lg" %>
      <%= image_tag "hero/circle/circle-path_13.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle/circle-path_14.svg", class:"circle-outline transparent-20 size-md" %>
      <%= image_tag "hero/circle/circle-path_15.svg", class:"circle-outline transparent-20 size-lg" %>
      <%= image_tag "hero/circle/circle-path_16.svg", class:"circle-outline size-sm" %>
      <%= image_tag "hero/circle-dots.svg", class:'circle-dots-1' %>
      <%= image_tag "hero/circle-dots.svg", class:'circle-dots-2' %>
      <div class="inner-circle">
        <div class="circled-quest">
          <div class="circled-quest-body">
            <% if quest&.id %>
            <h3><%= quest.creator&.username %></h3>
            <p><%= quest.title %></p>
            <div class="circled-quest-body__footer">
              <div class="footer-button">
                <%= image_tag "icons/solution.svg" %>
                <span><%= quest.solutions.count %></span>
              </div>
            </div>
            <%= link_to quest_path(quest), class: 'play-btn' do %>
              <span>Play now</span>
            <% end %>
          <% else %>
          <!-- <#%= image_tag 'logo_white.svg', style: 'opacity: 1; width: 200px;' %> -->
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="portal-wrapper">
      <%= image_tag "hero/portal2.svg" %>
      <div class="circle-lines-wrapper">
        <%= image_tag "hero/circle-lines-final.svg", class: 'circle-lines', style: 'opacity: .5;' %>
      </div>
      <div class="iota-logo-wrapper">
        <%= image_tag "icons/iota.svg", class: 'iota-logo' %>
      </div>
    </div>
  </div>
</div>

app/views/home/creators.html.erb
<% content_for :title, "Quests - Creators" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">Creators</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-white">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-30">
      <div class="col-md-6 ml-auto mr-auto">
        <h2 class="text-center">Who we are</h2>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <div class="box box-item">
            <%= image_tag "creators/huhn.png", class: 'mr-auto ml-auto' %>
            <h3 class="text-center">Sebastian</h3>
            <h6 class="text-center m-b-20" style="opacity: .5;">Development</h6>
            <p class="text-center">Sebastian (aka <a href="https://ecosystem.iota.org/users/huhn">huhn</a>) is developing the platform and takes care of both the backend and the communication with the tangle.</p>
          </div>
          <div class="box box-item">
            <%= image_tag "creators/r3p0x.png", class: 'mr-auto ml-auto' %>
            <h3 class="text-center">Sven</h3>
            <h6 class="text-center m-b-20" style="opacity: .5;">Design</h6>
            <p class="text-center">Sven (aka <a href="https://ecosystem.iota.org/users/rep0x">r3p0x</a>) is a passionate designer and frontend developer, focussing on graphic, UI / UX design.</p>
          </div>
        </div>
        <div class="d-flex justify-content-center m-t-30">
          <a href="mailto: quests@worldofmind.org?subject=Request to join the team&body=Tell us something about you and your background. Don't forget to let us know why you would like to join the team!" class="btn btn-primary">Become a creator</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/get_started.html.erb
<% content_for :title, "Quests - Get started" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="m-b-20">Get started</h1>
        <a href="mailto: quests@worldofmind.org?subject=I have a question" class="btn btn-dark">Ask us a question</a>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-30 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">SOLUTION</h2>
        <h3 class="text-center">How to solve a quest?</h3>
        <%= render "shared/ornaments/divider" %>
        <ol>
          <li>Find a quest which you can solve.</li>
          <li>Suggest a solution, add your IOTA address.</li>
          <li>If the quest creator accepts your solution, you will get the donations.</li>
        </ol>
        <a href="<%= quests_path %>" class="btn btn-primary m-t-30">Discover quests</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
  </div>
</div>

<div class="section content justify-content-start decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-30 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">CREATION</h2>
        <h3 class="text-center">How to create a quest?</h3>
        <%= render "shared/ornaments/divider" %>
        <ol>
          <li><%= link_to "Sign In", new_user_session_path %>, or <%= link_to "create an account", new_user_registration_path %>.</li>
          <li>Go to <%= link_to "create a quest", new_quest_url %> - Set a quest title and describe your quest then create it.</li>
          <li>Send some IOTA's to the quest address.</li>
          <li>Share the quest link with your people and wait for some solutions.</li>
          <li>Payout the solution, which you want to pay.</li>
        </ol>
        <p>The winner takes it all ... but just for the beginning! The IOTA's will be distributed in the future.</p>
        <a href="<%= new_quest_path %>" class="btn btn-primary m-t-30">Create your quest</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% content_for :title, "Quests - Home" %>

<div class="section section--hero hero" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h1 class="title m-t-0">Quest Playground</h1>
        <h2>Stop working. Start playing.</h2>
        <p>Quests is the worlds first platform where you can earn IOTA for solving issues or incentivize issues to get them solved by others.</p>
        <ul class="link-list">
          <li><a href="/get_started" class="link-item">Get started</a></li>
          <li><%= link_to "New Quest", new_quest_path, class: "link-item" %></li>
        </ul>
        <div class="kpi-wrapper">
           <div class="kpi-box" data-id="tab-open-quests">
             <h2><%= @open_quest_count || 0 %></h2>
             <h6>Open Quests</h6>
           </div>
           <div class="kpi-box" data-id="tab-solved-quests">
             <h2><%= @solved_quest_count || 0 %></h2>
             <h6>Solved Quests</h6>
           </div>
         </div>
        <div class="caret-down m-t-30" id="caret-down">
          <%= image_tag "icons/caret.svg" %>
        </div>
      </div>
      <div class="col-md-7">
      </div>
    </div>
  </div>
  <%= render "home/hero_animation", quest: @hero_quest %>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1" id="what-we-do">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">FEATURES</h2>
        <h3 class="text-center">WHAT WE DO TO HELP YOU</h3>
        <%= render "shared/ornaments/divider" %>
        <p class="text-center">Quests is a platform to incentivize tasks, issues, user stories or however you and your team call things that needs to be done - either way we call them quests. A quest is a bounty to solve an issue. If you cannot solve a quest on your own or simply don't have the time to do so - just fund some IOTA tokens to it. We just hit the beta release but you already can create, incentivize and payout quests. Good luck and have fun!</p>
        <a href="<%= new_quest_path %>" class="btn btn-primary m-t-30">Create a quest</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/pin.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Quests</h3>
            <p class="text-center">Create a detailed quest description and define what it means to you to call it "done". Then simply fund some IOTA tokens to it and wait for the proper solution.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/solution.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Solutions</h3>
            <p class="text-center">Anybody can suggest solutions to quests anonymously or as an authenticated user. Either way your solution needs to have a valid IOTA address in order to get the bounty.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/wallet.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">IOTA Payouts</h3>
            <p class="text-center">The creator of a quest can payout the bounty to the very best solution. The winner takes it all, but for sure just for now.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function (){
    $("#caret-down").click(function (){
      $('html, body').animate({
        scrollTop: $("#what-we-do").offset().top
      }, 600);
    });
  });
</script>

app/views/home/roadmap.html.erb
<% content_for :title, "Quests - Roadmap" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">Roadmap</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">Doing</h2>
        <h3 class="text-center">WHAT WE ARE WORKING ON</h3>
        <%= render "shared/ornaments/divider" %>
        <p class="text-center">We are always working on something, but it means a lot to us to share with you what is currently in our mind. This is because of two reasons. One, we want to be a transparent organisation and two, we want to give you the opportunity to share your thoughts and those of you who want to help us testing the opportunity to become a beta tester.</p>
        <a href="mailto: quests@worldofmind.org?subject=Request for beta testing&body=Tell us something about you and why you would like to help us testing!" class="btn btn-primary m-t-30">Help us testing</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/network.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Distribution</h3>
            <p class="text-center">A mechanismn to distrubte IOTA to the collaborators will be added.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/reply.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Reply</h3>
            <p class="text-center">A feature to discuss a quest will be added.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section content justify-content-start decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">Todo</h2>
        <h3 class="text-center">WHAT COMES NEXT</h3>
        <%= render "shared/ornaments/divider" %>
        <p class="text-center">Besides the features we are currently working on, we also want to let you know what we plan to do next. Most importantly we want to encourage you to share your prorities as a user. If you think there is something missing or one of those features is really important to you - don't hesitate to let us know!</p>
        <a href="mailto: quests@worldofmind.org?subject=Suggestion for further development&body=Describe your suggestions detailed here." class="btn btn-primary m-t-30">Suggest your ideas</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <div class="box box-item">
            <%= image_tag "illustrations/discover.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Discover</h3>
            <p class="text-center">A page to discover and filter all quests will be added.</p>
          </div>
          <div class="box box-item">
            <%= image_tag "illustrations/search.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Search</h3>
            <p class="text-center">A feature to search for quests by search criteria will be added.</p>
          </div>
          <div class="box box-item">
            <%= image_tag "illustrations/game.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Gamification</h3>
            <p class="text-center">A feature to value contributions to quests with inventices will be added.</p>
          </div>
          <div class="box box-item">
            <%= image_tag "illustrations/alert.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Notifications</h3>
            <p class="text-center">A feature to notify users about new quests and updates will be added.</p>
          </div>
          <div class="box box-item">
            <%= image_tag "illustrations/user.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Profile</h3>
            <p class="text-center">A feature to show users infos and efforts to quests will be added.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">Done</h2>
        <h3 class="text-center">WHAT has been achieved already</h3>
        <%= render "shared/ornaments/divider" %>
        <p class="text-center">What does "done" mean? The definition of done is quite complex since no thing will ever be absolutely done. Still we define our definition of done for all the features we are working on and someday each of them needs to be delivered in order to give you guys value. But if you find a bug or have an idea to improve something, please drop us a line! </p>
        <a href="mailto: quests@worldofmind.org?subject=Bug report&body=Describe your bug here and don't forget to give us some infos about your device and browser." class="btn btn-primary m-t-30">Report a bug</a>
      </div>
      <%= render "shared/ornaments/bg-big" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/heart.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Branding</h3>
            <p class="text-center">The branding process including a corporate identity has been finished.</p>
          </div>
          <div class=" box box-item box-dark">
            <%= image_tag "illustrations/webpage.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Landing Page</h3>
            <p class="text-center">The landing page for the beta release has been finished.</p>
          </div>
          <div class=" box box-item box-dark">
            <%= image_tag "illustrations/shield.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Authentication</h3>
            <p class="text-center">Autheticate users including account settings has been finished.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/pin.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Quests</h3>
            <p class="text-center">The ability to manage quests with basic details has been finished.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/solution.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">Solutions</h3>
            <p class="text-center">The ability to add a solution to a quest has been finished.</p>
          </div>
          <div class="box box-item box-dark">
            <%= image_tag "illustrations/wallet.svg", class: 'circled-box-image mr-auto ml-auto' %>
            <h3 class="text-center">IOTA Payout</h3>
            <p class="text-center">The ability to payout one solution creator with IOTA tokens has been finished.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>