config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  mount ActionCable.server => '/cable'
  resources :quests do
    resources :solutions do
       post 'payout'
     end
  end
  get :next_quest, to: 'quests#next'

  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/get_started', to: 'home#get_started'
  get '/creators', to: 'home#creators'
  get '/roadmap', to: 'home#roadmap'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ### API ROUTES
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post '/login', to: 'auth#login'
      resources :quests
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :quests
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = @current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" data_type="title">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if project.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', project, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <div class="form-actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>

    <% if project.persisted? %>
      <%= link_to "Cancel", project, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", projects_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Projects - Edit Project" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">Edit Project</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-6 ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container">
          <%= link_to 'Back', projects_path(@project) %>
        </div>
        <div class="box">
          <%= render 'form', project: @project %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects - Discover" %>
<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1>Discover</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start bg-darker decoration-1">
  <div class="container m-t-100 m-b-100">
    <div class="row m-b-50 row-decoration">
      <div class="col-lg-6 col-md-8 ml-auto mr-auto decorator d-flex flex-column align-items-center">
        <h2 class="text-center">Projects</h2>
        <a href="<%= new_project_path %>" class="btn btn-primary m-t-30">Create your project</a>
      </div>
      <%= render "shared/ornaments/bg-small" %>
    </div>
    <div class="row">
      <div class="col-md">
        <div class="box-list">
          <% @projects.each do |project| %>
          <a href="<%= project_path(project) %>" class="box box-item box-dark linked align-items-start justify-content-between">
            <div class="box-body">
              <h4><%= project.name %></h4>
              <span style="opacity: .5;">Created by: <%= project.user.username %></span>
            </div>
            <div class="box-footer">
             
            </div>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "Projects - Create a project" %>

<div class="section page-title bg-primary" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center">New project</h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-6 ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container">
          <%= link_to root_path do %>Back to Home<% end %>
        </div>
        <div class="box">
          <%= render 'form', project: @project %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :title, "Projects -  #{ @project.name}" %>

<div class="section page-title bg-primary p-t-25 p-b-100" id="hero">
  <div class="container">
    <div class="row">
      <div class="col-md">
        <h1 class="text-center"><%= @project.name %></h1>
      </div>
    </div>
  </div>
  <div class="waves">
    <%= image_tag "decoration/waves.svg" %>
  </div>
  <div class="waves rotate">
    <%= image_tag "decoration/waves.svg" %>
  </div>
</div>

<div class="section content justify-content-start pull-top">
  <div class="container">
    <div class="row">
      <div class="col-lg ml-auto mr-auto breadcrumb-wrapper">
        <div class="breadcrumb-container breadcrumb-container__pull-top">
          <%= link_to root_path do %>Back to Home<% end %>
        </div>
        <div class="box m-b-30">
          <% if current_user&.id == @project.user_id %>
          <div class="box-menu top-right">
            <%= link_to edit_project_path(@project), id:'edit-btn', class: 'btn btn-primary btn-icon', data: {toggle: 'tooltip', placement: 'bottom'}, title: "Edit your project" do %>
              <%= image_tag "icons/edit.svg" %>
            <% end %>
          </div>
          <% end %>
          <div class="box-body">
            <div id="countdown" class="box-countdown mr-auto ml-auto" >
              <h5 class="m-b-0" style="">Created by <%= @project.user.username %>, <%= time_ago_in_words @project.created_at %> ago</h5>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>